version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 chat_app.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] *
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: