# Generated by Django 4.2.7 on 2025-10-16 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatroom_created_by_chatroom_is_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activeuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='room',
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_group',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('group', 'Group Chat'), ('private', 'Private Chat')], default='group', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, default=0.0005387205387205387, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('chat_type', 'group')), fields=('chat_type', 'name'), name='unique_group_chat_name'),
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_participants', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'user')},
        ),
    ]
