# Generated by Django 4.2.7 on 2025-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roomparticipant_alter_activeuser_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='unique_group_chat_name',
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
